#ifndef PARAMS_H
#define PARAMS_H

#define CMAQ_PAR_REGION_NUM           17
#define CMAQ_PAR_SECTOR_NUM           5
#define CMAQ_PAR_CTRLMAX_NUM          CMAQ_PAR_REGION_NUM*CMAQ_PAR_SECTOR_NUM
#define CMAQ_PAR_SPECIES_NUM          6
#define CMAQ_PAR_ROW_NUM              82
#define CMAQ_PAR_COL_NUM              67

#define UNET_PAR_ROW_NUM              128
#define UNET_PAR_COL_NUM              96

#define UNET_PAR_0_DENSE_IN_DIM      1
#define UNET_PAR_0_DENSE_OUT_DIM     128

#define UNET_PAR_1_CONV2D_KERNEL_Y    3
#define UNET_PAR_1_CONV2D_KERNEL_X    3
#define UNET_PAR_1_CONV2D_IN_FILTER   5
#define UNET_PAR_1_CONV2D_OUT_FILTER  20

#define UNET_PAR_2_DENSE_IN_DIM      128
#define UNET_PAR_2_DENSE_OUT_DIM     20

#define UNET_PAR_3_BATCH_NORM_GAMMA        20
#define UNET_PAR_3_BATCH_NORM_BETA         20
#define UNET_PAR_3_BATCH_NORM_MEAN         20
#define UNET_PAR_3_BATCH_NORM_VARIANCE     20

#define UNET_PAR_4_CONV2D_KERNEL_Y    3
#define UNET_PAR_4_CONV2D_KERNEL_X    3
#define UNET_PAR_4_CONV2D_IN_FILTER   20
#define UNET_PAR_4_CONV2D_OUT_FILTER  20

#define UNET_PAR_5_BATCH_NORM_GAMMA        20
#define UNET_PAR_5_BATCH_NORM_BETA         20
#define UNET_PAR_5_BATCH_NORM_MEAN         20
#define UNET_PAR_5_BATCH_NORM_VARIANCE     20

#define UNET_PAR_6_CONV2D_KERNEL_Y    3
#define UNET_PAR_6_CONV2D_KERNEL_X    3
#define UNET_PAR_6_CONV2D_IN_FILTER   20
#define UNET_PAR_6_CONV2D_OUT_FILTER  40

#define UNET_PAR_7_DENSE_IN_DIM      128
#define UNET_PAR_7_DENSE_OUT_DIM     40

#define UNET_PAR_8_BATCH_NORM_GAMMA        40
#define UNET_PAR_8_BATCH_NORM_BETA         40
#define UNET_PAR_8_BATCH_NORM_MEAN         40
#define UNET_PAR_8_BATCH_NORM_VARIANCE     40

#define UNET_PAR_9_CONV2D_KERNEL_Y    3
#define UNET_PAR_9_CONV2D_KERNEL_X    3
#define UNET_PAR_9_CONV2D_IN_FILTER   40
#define UNET_PAR_9_CONV2D_OUT_FILTER  40

#define UNET_PAR_10_BATCH_NORM_GAMMA        40
#define UNET_PAR_10_BATCH_NORM_BETA         40
#define UNET_PAR_10_BATCH_NORM_MEAN         40
#define UNET_PAR_10_BATCH_NORM_VARIANCE     40

#define UNET_PAR_11_CONV2D_KERNEL_Y    3
#define UNET_PAR_11_CONV2D_KERNEL_X    3
#define UNET_PAR_11_CONV2D_IN_FILTER   40
#define UNET_PAR_11_CONV2D_OUT_FILTER  80

#define UNET_PAR_12_DENSE_IN_DIM      128
#define UNET_PAR_12_DENSE_OUT_DIM     80

#define UNET_PAR_13_BATCH_NORM_GAMMA        80
#define UNET_PAR_13_BATCH_NORM_BETA         80
#define UNET_PAR_13_BATCH_NORM_MEAN         80
#define UNET_PAR_13_BATCH_NORM_VARIANCE     80

#define UNET_PAR_14_CONV2D_KERNEL_Y    3
#define UNET_PAR_14_CONV2D_KERNEL_X    3
#define UNET_PAR_14_CONV2D_IN_FILTER   80
#define UNET_PAR_14_CONV2D_OUT_FILTER  80

#define UNET_PAR_15_BATCH_NORM_GAMMA        80
#define UNET_PAR_15_BATCH_NORM_BETA         80
#define UNET_PAR_15_BATCH_NORM_MEAN         80
#define UNET_PAR_15_BATCH_NORM_VARIANCE     80

#define UNET_PAR_16_CONV2D_KERNEL_Y    3
#define UNET_PAR_16_CONV2D_KERNEL_X    3
#define UNET_PAR_16_CONV2D_IN_FILTER   80
#define UNET_PAR_16_CONV2D_OUT_FILTER  160

#define UNET_PAR_17_DENSE_IN_DIM      128
#define UNET_PAR_17_DENSE_OUT_DIM     160

#define UNET_PAR_18_BATCH_NORM_GAMMA        160
#define UNET_PAR_18_BATCH_NORM_BETA         160
#define UNET_PAR_18_BATCH_NORM_MEAN         160
#define UNET_PAR_18_BATCH_NORM_VARIANCE     160

#define UNET_PAR_19_CONV2D_KERNEL_Y    3
#define UNET_PAR_19_CONV2D_KERNEL_X    3
#define UNET_PAR_19_CONV2D_IN_FILTER   160
#define UNET_PAR_19_CONV2D_OUT_FILTER  160

#define UNET_PAR_20_BATCH_NORM_GAMMA        160
#define UNET_PAR_20_BATCH_NORM_BETA         160
#define UNET_PAR_20_BATCH_NORM_MEAN         160
#define UNET_PAR_20_BATCH_NORM_VARIANCE     160

#define UNET_PAR_21_CONV2D_KERNEL_Y    3
#define UNET_PAR_21_CONV2D_KERNEL_X    3
#define UNET_PAR_21_CONV2D_IN_FILTER   160
#define UNET_PAR_21_CONV2D_OUT_FILTER  320

#define UNET_PAR_22_DENSE_IN_DIM      128
#define UNET_PAR_22_DENSE_OUT_DIM     320

#define UNET_PAR_23_BATCH_NORM_GAMMA        320
#define UNET_PAR_23_BATCH_NORM_BETA         320
#define UNET_PAR_23_BATCH_NORM_MEAN         320
#define UNET_PAR_23_BATCH_NORM_VARIANCE     320

#define UNET_PAR_24_CONV2D_KERNEL_Y    3
#define UNET_PAR_24_CONV2D_KERNEL_X    3
#define UNET_PAR_24_CONV2D_IN_FILTER   320
#define UNET_PAR_24_CONV2D_OUT_FILTER  320

#define UNET_PAR_25_BATCH_NORM_GAMMA        320
#define UNET_PAR_25_BATCH_NORM_BETA         320
#define UNET_PAR_25_BATCH_NORM_MEAN         320
#define UNET_PAR_25_BATCH_NORM_VARIANCE     320

#define UNET_PAR_26_CONV2D_TRANSPOSE_KERNEL_Y    3
#define UNET_PAR_26_CONV2D_TRANSPOSE_KERNEL_X    3
#define UNET_PAR_26_CONV2D_TRANSPOSE_IN_FILTER   320
#define UNET_PAR_26_CONV2D_TRANSPOSE_OUT_FILTER  160

#define UNET_PAR_27_BATCH_NORM_GAMMA        160
#define UNET_PAR_27_BATCH_NORM_BETA         160
#define UNET_PAR_27_BATCH_NORM_MEAN         160
#define UNET_PAR_27_BATCH_NORM_VARIANCE     160

#define UNET_PAR_28_DENSE_IN_DIM      128
#define UNET_PAR_28_DENSE_OUT_DIM     160

#define UNET_PAR_29_CONV2D_KERNEL_Y    3
#define UNET_PAR_29_CONV2D_KERNEL_X    3
#define UNET_PAR_29_CONV2D_IN_FILTER   320
#define UNET_PAR_29_CONV2D_OUT_FILTER  160

#define UNET_PAR_30_BATCH_NORM_GAMMA        160
#define UNET_PAR_30_BATCH_NORM_BETA         160
#define UNET_PAR_30_BATCH_NORM_MEAN         160
#define UNET_PAR_30_BATCH_NORM_VARIANCE     160

#define UNET_PAR_31_CONV2D_TRANSPOSE_KERNEL_Y    3
#define UNET_PAR_31_CONV2D_TRANSPOSE_KERNEL_X    3
#define UNET_PAR_31_CONV2D_TRANSPOSE_IN_FILTER   160
#define UNET_PAR_31_CONV2D_TRANSPOSE_OUT_FILTER  80

#define UNET_PAR_32_BATCH_NORM_GAMMA        80
#define UNET_PAR_32_BATCH_NORM_BETA         80
#define UNET_PAR_32_BATCH_NORM_MEAN         80
#define UNET_PAR_32_BATCH_NORM_VARIANCE     80

#define UNET_PAR_33_DENSE_IN_DIM      128
#define UNET_PAR_33_DENSE_OUT_DIM     80

#define UNET_PAR_34_CONV2D_KERNEL_Y    3
#define UNET_PAR_34_CONV2D_KERNEL_X    3
#define UNET_PAR_34_CONV2D_IN_FILTER   160
#define UNET_PAR_34_CONV2D_OUT_FILTER  80

#define UNET_PAR_35_BATCH_NORM_GAMMA        80
#define UNET_PAR_35_BATCH_NORM_BETA         80
#define UNET_PAR_35_BATCH_NORM_MEAN         80
#define UNET_PAR_35_BATCH_NORM_VARIANCE     80

#define UNET_PAR_36_CONV2D_TRANSPOSE_KERNEL_Y    3
#define UNET_PAR_36_CONV2D_TRANSPOSE_KERNEL_X    3
#define UNET_PAR_36_CONV2D_TRANSPOSE_IN_FILTER   80
#define UNET_PAR_36_CONV2D_TRANSPOSE_OUT_FILTER  40

#define UNET_PAR_37_BATCH_NORM_GAMMA        40
#define UNET_PAR_37_BATCH_NORM_BETA         40
#define UNET_PAR_37_BATCH_NORM_MEAN         40
#define UNET_PAR_37_BATCH_NORM_VARIANCE     40

#define UNET_PAR_38_DENSE_IN_DIM      128
#define UNET_PAR_38_DENSE_OUT_DIM     40

#define UNET_PAR_39_CONV2D_KERNEL_Y    3
#define UNET_PAR_39_CONV2D_KERNEL_X    3
#define UNET_PAR_39_CONV2D_IN_FILTER   80
#define UNET_PAR_39_CONV2D_OUT_FILTER  40

#define UNET_PAR_40_BATCH_NORM_GAMMA        40
#define UNET_PAR_40_BATCH_NORM_BETA         40
#define UNET_PAR_40_BATCH_NORM_MEAN         40
#define UNET_PAR_40_BATCH_NORM_VARIANCE     40

#define UNET_PAR_41_CONV2D_KERNEL_Y    1
#define UNET_PAR_41_CONV2D_KERNEL_X    1
#define UNET_PAR_41_CONV2D_IN_FILTER   40
#define UNET_PAR_41_CONV2D_OUT_FILTER  1


#endif
