#ifndef PARAMS_H
#define PARAMS_H

#define CMAQ_PAR_REGION_NUM           17
#define CMAQ_PAR_SECTOR_NUM           7
#define CMAQ_PAR_CTRLMAX_NUM          CMAQ_PAR_REGION_NUM*CMAQ_PAR_SECTOR_NUM
#define CMAQ_PAR_SPECIES_NUM          6
#define CMAQ_PAR_ROW_NUM              82
#define CMAQ_PAR_COL_NUM              67

#define UNET_PAR_ROW_NUM              96
#define UNET_PAR_COL_NUM              64

#define UNET_PAR_0_CONV2D_KERNEL_Y    3
#define UNET_PAR_0_CONV2D_KERNEL_X    3
#define UNET_PAR_0_CONV2D_IN_FILTER   7
#define UNET_PAR_0_CONV2D_OUT_FILTER  10

#define UNET_PAR_1_CONV2D_KERNEL_Y    3
#define UNET_PAR_1_CONV2D_KERNEL_X    3
#define UNET_PAR_1_CONV2D_IN_FILTER   7
#define UNET_PAR_1_CONV2D_OUT_FILTER  10

#define UNET_PAR_2_BATCH_NORMALIZATION_GAMMA        10
#define UNET_PAR_2_BATCH_NORMALIZATION_BETA         10
#define UNET_PAR_2_BATCH_NORMALIZATION_MEAN         10
#define UNET_PAR_2_BATCH_NORMALIZATION_VARIANCE     10

#define UNET_PAR_3_CONV2D_KERNEL_Y    3
#define UNET_PAR_3_CONV2D_KERNEL_X    3
#define UNET_PAR_3_CONV2D_IN_FILTER   10
#define UNET_PAR_3_CONV2D_OUT_FILTER  10

#define UNET_PAR_4_BATCH_NORMALIZATION_GAMMA        10
#define UNET_PAR_4_BATCH_NORMALIZATION_BETA         10
#define UNET_PAR_4_BATCH_NORMALIZATION_MEAN         10
#define UNET_PAR_4_BATCH_NORMALIZATION_VARIANCE     10

#define UNET_PAR_5_CONV2D_KERNEL_Y    3
#define UNET_PAR_5_CONV2D_KERNEL_X    3
#define UNET_PAR_5_CONV2D_IN_FILTER   10
#define UNET_PAR_5_CONV2D_OUT_FILTER  20

#define UNET_PAR_6_CONV2D_KERNEL_Y    3
#define UNET_PAR_6_CONV2D_KERNEL_X    3
#define UNET_PAR_6_CONV2D_IN_FILTER   7
#define UNET_PAR_6_CONV2D_OUT_FILTER  20

#define UNET_PAR_7_BATCH_NORMALIZATION_GAMMA        20
#define UNET_PAR_7_BATCH_NORMALIZATION_BETA         20
#define UNET_PAR_7_BATCH_NORMALIZATION_MEAN         20
#define UNET_PAR_7_BATCH_NORMALIZATION_VARIANCE     20

#define UNET_PAR_8_CONV2D_KERNEL_Y    3
#define UNET_PAR_8_CONV2D_KERNEL_X    3
#define UNET_PAR_8_CONV2D_IN_FILTER   20
#define UNET_PAR_8_CONV2D_OUT_FILTER  20

#define UNET_PAR_9_BATCH_NORMALIZATION_GAMMA        20
#define UNET_PAR_9_BATCH_NORMALIZATION_BETA         20
#define UNET_PAR_9_BATCH_NORMALIZATION_MEAN         20
#define UNET_PAR_9_BATCH_NORMALIZATION_VARIANCE     20

#define UNET_PAR_10_CONV2D_KERNEL_Y    3
#define UNET_PAR_10_CONV2D_KERNEL_X    3
#define UNET_PAR_10_CONV2D_IN_FILTER   20
#define UNET_PAR_10_CONV2D_OUT_FILTER  40

#define UNET_PAR_11_CONV2D_KERNEL_Y    3
#define UNET_PAR_11_CONV2D_KERNEL_X    3
#define UNET_PAR_11_CONV2D_IN_FILTER   7
#define UNET_PAR_11_CONV2D_OUT_FILTER  40

#define UNET_PAR_12_BATCH_NORMALIZATION_GAMMA        40
#define UNET_PAR_12_BATCH_NORMALIZATION_BETA         40
#define UNET_PAR_12_BATCH_NORMALIZATION_MEAN         40
#define UNET_PAR_12_BATCH_NORMALIZATION_VARIANCE     40

#define UNET_PAR_13_CONV2D_KERNEL_Y    3
#define UNET_PAR_13_CONV2D_KERNEL_X    3
#define UNET_PAR_13_CONV2D_IN_FILTER   40
#define UNET_PAR_13_CONV2D_OUT_FILTER  40

#define UNET_PAR_14_BATCH_NORMALIZATION_GAMMA        40
#define UNET_PAR_14_BATCH_NORMALIZATION_BETA         40
#define UNET_PAR_14_BATCH_NORMALIZATION_MEAN         40
#define UNET_PAR_14_BATCH_NORMALIZATION_VARIANCE     40

#define UNET_PAR_15_CONV2D_KERNEL_Y    3
#define UNET_PAR_15_CONV2D_KERNEL_X    3
#define UNET_PAR_15_CONV2D_IN_FILTER   40
#define UNET_PAR_15_CONV2D_OUT_FILTER  80

#define UNET_PAR_16_CONV2D_KERNEL_Y    3
#define UNET_PAR_16_CONV2D_KERNEL_X    3
#define UNET_PAR_16_CONV2D_IN_FILTER   7
#define UNET_PAR_16_CONV2D_OUT_FILTER  80

#define UNET_PAR_17_BATCH_NORMALIZATION_GAMMA        80
#define UNET_PAR_17_BATCH_NORMALIZATION_BETA         80
#define UNET_PAR_17_BATCH_NORMALIZATION_MEAN         80
#define UNET_PAR_17_BATCH_NORMALIZATION_VARIANCE     80

#define UNET_PAR_18_CONV2D_KERNEL_Y    3
#define UNET_PAR_18_CONV2D_KERNEL_X    3
#define UNET_PAR_18_CONV2D_IN_FILTER   80
#define UNET_PAR_18_CONV2D_OUT_FILTER  80

#define UNET_PAR_19_BATCH_NORMALIZATION_GAMMA        80
#define UNET_PAR_19_BATCH_NORMALIZATION_BETA         80
#define UNET_PAR_19_BATCH_NORMALIZATION_MEAN         80
#define UNET_PAR_19_BATCH_NORMALIZATION_VARIANCE     80

#define UNET_PAR_20_CONV2D_KERNEL_Y    3
#define UNET_PAR_20_CONV2D_KERNEL_X    3
#define UNET_PAR_20_CONV2D_IN_FILTER   80
#define UNET_PAR_20_CONV2D_OUT_FILTER  160

#define UNET_PAR_21_CONV2D_KERNEL_Y    3
#define UNET_PAR_21_CONV2D_KERNEL_X    3
#define UNET_PAR_21_CONV2D_IN_FILTER   7
#define UNET_PAR_21_CONV2D_OUT_FILTER  160

#define UNET_PAR_22_BATCH_NORMALIZATION_GAMMA        160
#define UNET_PAR_22_BATCH_NORMALIZATION_BETA         160
#define UNET_PAR_22_BATCH_NORMALIZATION_MEAN         160
#define UNET_PAR_22_BATCH_NORMALIZATION_VARIANCE     160

#define UNET_PAR_23_CONV2D_KERNEL_Y    3
#define UNET_PAR_23_CONV2D_KERNEL_X    3
#define UNET_PAR_23_CONV2D_IN_FILTER   160
#define UNET_PAR_23_CONV2D_OUT_FILTER  160

#define UNET_PAR_24_BATCH_NORMALIZATION_GAMMA        160
#define UNET_PAR_24_BATCH_NORMALIZATION_BETA         160
#define UNET_PAR_24_BATCH_NORMALIZATION_MEAN         160
#define UNET_PAR_24_BATCH_NORMALIZATION_VARIANCE     160

#define UNET_PAR_25_CONV2D_TRANSPOSE_KERNEL_Y    3
#define UNET_PAR_25_CONV2D_TRANSPOSE_KERNEL_X    3
#define UNET_PAR_25_CONV2D_TRANSPOSE_IN_FILTER   160
#define UNET_PAR_25_CONV2D_TRANSPOSE_OUT_FILTER  80

#define UNET_PAR_26_BATCH_NORMALIZATION_GAMMA        80
#define UNET_PAR_26_BATCH_NORMALIZATION_BETA         80
#define UNET_PAR_26_BATCH_NORMALIZATION_MEAN         80
#define UNET_PAR_26_BATCH_NORMALIZATION_VARIANCE     80

#define UNET_PAR_27_CONV2D_KERNEL_Y    3
#define UNET_PAR_27_CONV2D_KERNEL_X    3
#define UNET_PAR_27_CONV2D_IN_FILTER   7
#define UNET_PAR_27_CONV2D_OUT_FILTER  80

#define UNET_PAR_28_CONV2D_KERNEL_Y    3
#define UNET_PAR_28_CONV2D_KERNEL_X    3
#define UNET_PAR_28_CONV2D_IN_FILTER   160
#define UNET_PAR_28_CONV2D_OUT_FILTER  80

#define UNET_PAR_29_BATCH_NORMALIZATION_GAMMA        80
#define UNET_PAR_29_BATCH_NORMALIZATION_BETA         80
#define UNET_PAR_29_BATCH_NORMALIZATION_MEAN         80
#define UNET_PAR_29_BATCH_NORMALIZATION_VARIANCE     80

#define UNET_PAR_30_CONV2D_TRANSPOSE_KERNEL_Y    3
#define UNET_PAR_30_CONV2D_TRANSPOSE_KERNEL_X    3
#define UNET_PAR_30_CONV2D_TRANSPOSE_IN_FILTER   80
#define UNET_PAR_30_CONV2D_TRANSPOSE_OUT_FILTER  40

#define UNET_PAR_31_BATCH_NORMALIZATION_GAMMA        40
#define UNET_PAR_31_BATCH_NORMALIZATION_BETA         40
#define UNET_PAR_31_BATCH_NORMALIZATION_MEAN         40
#define UNET_PAR_31_BATCH_NORMALIZATION_VARIANCE     40

#define UNET_PAR_32_CONV2D_KERNEL_Y    3
#define UNET_PAR_32_CONV2D_KERNEL_X    3
#define UNET_PAR_32_CONV2D_IN_FILTER   7
#define UNET_PAR_32_CONV2D_OUT_FILTER  40

#define UNET_PAR_33_CONV2D_KERNEL_Y    3
#define UNET_PAR_33_CONV2D_KERNEL_X    3
#define UNET_PAR_33_CONV2D_IN_FILTER   80
#define UNET_PAR_33_CONV2D_OUT_FILTER  40

#define UNET_PAR_34_BATCH_NORMALIZATION_GAMMA        40
#define UNET_PAR_34_BATCH_NORMALIZATION_BETA         40
#define UNET_PAR_34_BATCH_NORMALIZATION_MEAN         40
#define UNET_PAR_34_BATCH_NORMALIZATION_VARIANCE     40

#define UNET_PAR_35_CONV2D_TRANSPOSE_KERNEL_Y    3
#define UNET_PAR_35_CONV2D_TRANSPOSE_KERNEL_X    3
#define UNET_PAR_35_CONV2D_TRANSPOSE_IN_FILTER   40
#define UNET_PAR_35_CONV2D_TRANSPOSE_OUT_FILTER  20

#define UNET_PAR_36_BATCH_NORMALIZATION_GAMMA        20
#define UNET_PAR_36_BATCH_NORMALIZATION_BETA         20
#define UNET_PAR_36_BATCH_NORMALIZATION_MEAN         20
#define UNET_PAR_36_BATCH_NORMALIZATION_VARIANCE     20

#define UNET_PAR_37_CONV2D_KERNEL_Y    3
#define UNET_PAR_37_CONV2D_KERNEL_X    3
#define UNET_PAR_37_CONV2D_IN_FILTER   7
#define UNET_PAR_37_CONV2D_OUT_FILTER  20

#define UNET_PAR_38_CONV2D_KERNEL_Y    3
#define UNET_PAR_38_CONV2D_KERNEL_X    3
#define UNET_PAR_38_CONV2D_IN_FILTER   40
#define UNET_PAR_38_CONV2D_OUT_FILTER  20

#define UNET_PAR_39_BATCH_NORMALIZATION_GAMMA        20
#define UNET_PAR_39_BATCH_NORMALIZATION_BETA         20
#define UNET_PAR_39_BATCH_NORMALIZATION_MEAN         20
#define UNET_PAR_39_BATCH_NORMALIZATION_VARIANCE     20

#define UNET_PAR_40_CONV2D_TRANSPOSE_KERNEL_Y    3
#define UNET_PAR_40_CONV2D_TRANSPOSE_KERNEL_X    3
#define UNET_PAR_40_CONV2D_TRANSPOSE_IN_FILTER   20
#define UNET_PAR_40_CONV2D_TRANSPOSE_OUT_FILTER  10

#define UNET_PAR_41_BATCH_NORMALIZATION_GAMMA        10
#define UNET_PAR_41_BATCH_NORMALIZATION_BETA         10
#define UNET_PAR_41_BATCH_NORMALIZATION_MEAN         10
#define UNET_PAR_41_BATCH_NORMALIZATION_VARIANCE     10

#define UNET_PAR_42_CONV2D_KERNEL_Y    3
#define UNET_PAR_42_CONV2D_KERNEL_X    3
#define UNET_PAR_42_CONV2D_IN_FILTER   7
#define UNET_PAR_42_CONV2D_OUT_FILTER  10

#define UNET_PAR_43_CONV2D_KERNEL_Y    3
#define UNET_PAR_43_CONV2D_KERNEL_X    3
#define UNET_PAR_43_CONV2D_IN_FILTER   20
#define UNET_PAR_43_CONV2D_OUT_FILTER  10

#define UNET_PAR_44_BATCH_NORMALIZATION_GAMMA        10
#define UNET_PAR_44_BATCH_NORMALIZATION_BETA         10
#define UNET_PAR_44_BATCH_NORMALIZATION_MEAN         10
#define UNET_PAR_44_BATCH_NORMALIZATION_VARIANCE     10

#define UNET_PAR_45_CONV2D_KERNEL_Y    1
#define UNET_PAR_45_CONV2D_KERNEL_X    1
#define UNET_PAR_45_CONV2D_IN_FILTER   10
#define UNET_PAR_45_CONV2D_OUT_FILTER  1


#endif
